import React from "react";
import Image from "next/image";

export const metadata = {
  title: "About | Md. Asaduzzaman Akash",
  description: "Generated by create next app",
};

export default function AboutPage() {
  return (
    <main className="mx-auto flex w-full  max-w-3xl flex-1">
      <div className="flex flex-col space-y-4 px-6 pt-24 sm:pt-28  md:space-y-0 md:px-0">
        <h1 className="bg-gradient-to-r from-purple-600 via-pink-600 to-blue-600 bg-clip-text text-center text-4xl font-bold  text-transparent md:pb-4 md:text-6xl">
          About.
        </h1>
        <div className="flex flex-col items-center space-y-5  md:flex-row md:space-x-4 md:space-y-0 ">
          <div className="md:mt-2 md:w-1/2">
            <Image
              src="https://media.licdn.com/dms/image/D4E03AQFouQzh7J_CiQ/profile-displayphoto-shrink_800_800/0/1666373145254?e=1687996800&v=beta&t=lXqWJGriZB93apQQYavEy9cpfv6TmnOTCEFUethMejQ"
              alt=""
              width={300}
              height={300}
              className="shadow-2xl "
            />
          </div>
          <div className="text-center text-stone-100 md:mt-2 md:w-1/2 md:text-left">
            <p className="text-lg leading-7 ">
              Hi, my name is{" "}
              <span className="font-semibold">Md. Asaduzzaman Akash</span>! I am
              a software engineer and front end developer based in{" "}
              <span className="font-semibold">Dhaka, Bangladesh.</span>
            </p>
            <br />
            <p className="text-lg leading-7">
              I have a wide range of hobbies and passions that keep me busy.
              From coding, creating websites, reading, watching cricket and
              traveling. I am always seeking new experiences and learning new
              things. I believe that you should{" "}
              <span className="bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-lg font-semibold text-transparent">
                never stop growing
              </span>{" "}
              and that&#39;s what I strive to do 🙂.
            </p>
            <br />
          </div>
        </div>
      </div>
    </main>
  );
}
